"""Schema Gate — blocks jobs with uncommitted schema changes (ARCH-015).

When a job's commit touches schema.sql, this gate pauses the job at
status='blocked' and pings Musa with the raw DDL so he can apply it via
Supabase MCP (apply_migration) or the SQL editor.

Why not auto-apply?
  The orchestrator holds no DB DDL credentials by design. Auto-applying
  DDL generated by an autonomous session is too risky (DROP/RENAME
  mistakes are unrecoverable). Block + escalate closes the silent-drift
  gap without handing over the keys.

What this prevents:
  TASK-032 shipped code selecting new columns plus schema.sql edits, but
  the live DB was never altered. Every subsequent poll would have
  silently 400'd inside a swallowed except. Orchestrator kept humming,
  queue quietly stalled. This gate would have caught it.

Gate applies to any repo in REPOS.json with a non-null
supabase_project_ref. Other repos (client schemas, etc.) are ignored.
"""

from __future__ import annotations

import asyncio
import logging

from context_loader import get_repo_config
from notification_router import get_chat_id

logger = logging.getLogger("wingmen.schema_gate")

_DDL_PREFIXES = ("alter ", "create ", "drop ", "grant ", "revoke ")


async def _git_stdout(repo_path: str, *args: str) -> str:
    proc = await asyncio.create_subprocess_exec(
        "git", *args,
        cwd=repo_path,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    try:
        stdout, _ = await asyncio.wait_for(proc.communicate(), timeout=15)
        return stdout.decode(errors="replace")
    except asyncio.TimeoutError:
        proc.kill()
        return ""


async def extract_schema_ddl(repo_path: str) -> list[str]:
    """Return DDL lines added to schema.sql in HEAD vs HEAD~1.

    Skips comments, blank lines, and non-DDL statements. Only picks up
    structural changes (alter/create/drop/grant/revoke) — seed data
    inserts are intentionally ignored here; those aren't blocking.
    """
    diff = await _git_stdout(repo_path, "diff", "HEAD~1", "HEAD", "--", "schema.sql")
    if not diff.strip():
        return []

    ddl: list[str] = []
    for line in diff.splitlines():
        if not line.startswith("+") or line.startswith("+++"):
            continue
        content = line[1:].strip()
        if not content or content.startswith("--"):
            continue
        if any(content.lower().startswith(kw) for kw in _DDL_PREFIXES):
            ddl.append(content)
    return ddl


async def check_and_block(
    supabase,
    repo_path: str,
    repo_name: str,
    job_id: int,
    job_description: str,
    bot=None,
) -> bool:
    """If HEAD touched schema.sql with DDL, block the job and escalate.

    Returns True if the job was blocked (caller should bail before
    marking completed). Returns False if there's nothing to gate on.
    """
    try:
        cfg = get_repo_config(repo_name)
    except ValueError:
        return False
    project_ref = cfg.get("supabase_project_ref")
    if not project_ref or project_ref == "FILL_IN":
        return False

    ddl = await extract_schema_ddl(repo_path)
    if not ddl:
        return False

    sql_block = "\n".join(ddl)
    logger.warning(f"Job #{job_id}: schema.sql DDL detected — blocking")

    try:
        await supabase.table("jobs").update({
            "status": "blocked",
            "result_summary": (
                f"Schema migration pending on project {project_ref} — see Telegram.\n\n"
                f"SQL:\n{sql_block[:1800]}"
            ),
        }).eq("id", job_id).execute()
    except Exception as e:
        logger.error(f"Failed to mark job {job_id} blocked: {e}")

    dedup_key = f"schema_gate:{job_id}"
    try:
        existing = await supabase.table("notification_log").select("id").eq(
            "dedup_key", dedup_key
        ).limit(1).execute()
        if existing.data:
            return True
    except Exception as e:
        logger.warning(f"Schema gate dedup check failed: {e}")

    cto_id = get_chat_id("cto")
    if not (bot and cto_id):
        return True

    # Message is addressed to CC-here or cai — either can apply via the
    # Supabase MCP without Musa having to paste SQL anywhere. Musa just
    # needs to forward this (or let cai see it on next poll) and /resume.
    migration_name = f"job_{job_id}_schema"
    msg = (
        f"\U0001f6a7 Schema migration pending — Job #{job_id} blocked\n\n"
        f"Repo: {repo_name}\n"
        f"Project: {project_ref}\n"
        f"Task: {job_description[:150]}\n\n"
        f"CC or cai: apply via Supabase MCP\n"
        f"  apply_migration(project_id=\"{project_ref}\", name=\"{migration_name}\", query=<SQL below>)\n\n"
        f"SQL:\n{sql_block[:2500]}\n\n"
        f"After apply: /resume {job_id}"
    )
    try:
        await bot.send_message(chat_id=cto_id, text=msg)
    except Exception as e:
        logger.error(f"Schema gate Telegram send failed: {e}")
    try:
        await supabase.table("notification_log").insert({
            "source": "schema_gate",
            "channel": "telegram",
            "recipient": cto_id,
            "message_text": msg[:3000],
            "dedup_key": dedup_key,
        }).execute()
    except Exception as e:
        logger.error(f"Schema gate log insert failed: {e}")

    return True
