-- 012_mamadah_second_brain.sql
-- Zahidah second-brain: add pgvector embeddings + source registry to existing mamadah_notes.
-- mamadah_notes already exists with 33 rows — ALTER only, no DROP.
-- CAI-RESP-355 | decided 2026-06-30 | decided_by=cai
--
-- Amanah constraints:
--   RLS on both tables, deny-all for public (service role bypasses RLS in Supabase)
--   Embeddings generated by Mac Studio BGE-M3 (100.104.36.27:8080) — no 3rd-party SaaS
--   Minimal data: extracted text only, raw files never stored in substrate

-- ── 1. Source registry (new) ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS mamadah_sources (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  chat_id      TEXT        NOT NULL,
  source_name  TEXT        NOT NULL DEFAULT 'untitled',
  source_type  TEXT        NOT NULL,
  content_hash TEXT        NOT NULL,  -- SHA-256 of raw bytes for dedup
  chunk_count  INT         NOT NULL DEFAULT 0,
  ingested_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS mamadah_sources_dedup_idx
  ON mamadah_sources(chat_id, content_hash);

CREATE INDEX IF NOT EXISTS mamadah_sources_chat_idx
  ON mamadah_sources(chat_id, ingested_at DESC);

-- ── 2. Extend mamadah_notes ───────────────────────────────────────────────────
-- Add embedding column (nullable — populated async by encoder; FTS is immediate fallback)
ALTER TABLE mamadah_notes
  ADD COLUMN IF NOT EXISTS embedding   vector(1024),
  ADD COLUMN IF NOT EXISTS chunk_index INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS source_id   UUID REFERENCES mamadah_sources(id) ON DELETE SET NULL;

-- FTS index on generated tsvector — existing mamadah_notes_fts index covers content only;
-- add source-aware index for filtered FTS
CREATE INDEX IF NOT EXISTS mamadah_notes_source_chunk_idx
  ON mamadah_notes(source_id, chunk_index)
  WHERE source_id IS NOT NULL;

-- Partial vector index — only rows with embeddings (skip nulls for ANN)
-- Activate once >100 rows have embeddings:
-- CREATE INDEX mamadah_notes_emb_idx ON mamadah_notes
--   USING ivfflat (embedding vector_cosine_ops) WITH (lists = 10)
--   WHERE embedding IS NOT NULL;

-- ── 3. RLS: service-role only ─────────────────────────────────────────────────
ALTER TABLE mamadah_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE mamadah_notes   ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "service_role_only_mamadah_sources" ON mamadah_sources;
DROP POLICY IF EXISTS "service_role_only_mamadah_notes"   ON mamadah_notes;

CREATE POLICY "service_role_only_mamadah_sources" ON mamadah_sources
  AS PERMISSIVE FOR ALL TO public USING (false);

CREATE POLICY "service_role_only_mamadah_notes" ON mamadah_notes
  AS PERMISSIVE FOR ALL TO public USING (false);

-- ── 4. Migration tracker ──────────────────────────────────────────────────────
INSERT INTO supabase_migrations.schema_migrations (version, name, statements)
VALUES ('20260630140000', '012_mamadah_second_brain', ARRAY[
  'CREATE TABLE mamadah_sources',
  'ALTER mamadah_notes: embedding vector(1024), chunk_index, source_id',
  'RLS deny-all public on both tables'
]) ON CONFLICT (version) DO NOTHING;
