-- migration 013: substrate RLS/grant lockdown (Track A) — backend-only substrate tables
-- Generated 2026-07-01. service_role + console_readonly + owner retain access; anon/authenticated/PUBLIC revoked.
BEGIN;
ALTER TABLE public."active_autonomous_loops" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "active_autonomous_loops_service_only" ON public."active_autonomous_loops"; CREATE POLICY "active_autonomous_loops_service_only" ON public."active_autonomous_loops" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "active_autonomous_loops_console_ro" ON public."active_autonomous_loops"; CREATE POLICY "active_autonomous_loops_console_ro" ON public."active_autonomous_loops" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."active_autonomous_loops" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."active_autonomous_loops" TO service_role;
GRANT SELECT ON public."active_autonomous_loops" TO console_readonly;
ALTER TABLE public."agent_context" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "service role only on agent_context" ON public."agent_context";
DROP POLICY IF EXISTS "agent_context_service_only" ON public."agent_context"; CREATE POLICY "agent_context_service_only" ON public."agent_context" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "agent_context_console_ro" ON public."agent_context"; CREATE POLICY "agent_context_console_ro" ON public."agent_context" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."agent_context" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."agent_context" TO service_role;
GRANT SELECT ON public."agent_context" TO console_readonly;
ALTER TABLE public."agent_messages" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "service role only on agent_messages" ON public."agent_messages";
DROP POLICY IF EXISTS "agent_messages_service_only" ON public."agent_messages"; CREATE POLICY "agent_messages_service_only" ON public."agent_messages" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "agent_messages_console_ro" ON public."agent_messages"; CREATE POLICY "agent_messages_console_ro" ON public."agent_messages" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."agent_messages" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."agent_messages" TO service_role;
GRANT SELECT ON public."agent_messages" TO console_readonly;
ALTER TABLE public."agent_status" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "agent_status_service_only" ON public."agent_status"; CREATE POLICY "agent_status_service_only" ON public."agent_status" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "agent_status_console_ro" ON public."agent_status"; CREATE POLICY "agent_status_console_ro" ON public."agent_status" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."agent_status" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."agent_status" TO service_role;
GRANT SELECT ON public."agent_status" TO console_readonly;
ALTER TABLE public."agent_status_history" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "agent_status_history_service_only" ON public."agent_status_history"; CREATE POLICY "agent_status_history_service_only" ON public."agent_status_history" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "agent_status_history_console_ro" ON public."agent_status_history"; CREATE POLICY "agent_status_history_console_ro" ON public."agent_status_history" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."agent_status_history" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."agent_status_history" TO service_role;
GRANT SELECT ON public."agent_status_history" TO console_readonly;
ALTER TABLE public."agent_status_identity_violations" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "agent_status_identity_violations_service_only" ON public."agent_status_identity_violations"; CREATE POLICY "agent_status_identity_violations_service_only" ON public."agent_status_identity_violations" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "agent_status_identity_violations_console_ro" ON public."agent_status_identity_violations"; CREATE POLICY "agent_status_identity_violations_console_ro" ON public."agent_status_identity_violations" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."agent_status_identity_violations" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."agent_status_identity_violations" TO service_role;
GRANT SELECT ON public."agent_status_identity_violations" TO console_readonly;
ALTER TABLE public."agents" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "service role only on agents" ON public."agents";
DROP POLICY IF EXISTS "agents_service_only" ON public."agents"; CREATE POLICY "agents_service_only" ON public."agents" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "agents_console_ro" ON public."agents"; CREATE POLICY "agents_console_ro" ON public."agents" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."agents" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."agents" TO service_role;
GRANT SELECT ON public."agents" TO console_readonly;
ALTER TABLE public."anchor_queue" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "service_role full access" ON public."anchor_queue";
DROP POLICY IF EXISTS "anchor_queue_service_only" ON public."anchor_queue"; CREATE POLICY "anchor_queue_service_only" ON public."anchor_queue" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anchor_queue_console_ro" ON public."anchor_queue"; CREATE POLICY "anchor_queue_console_ro" ON public."anchor_queue" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."anchor_queue" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."anchor_queue" TO service_role;
GRANT SELECT ON public."anchor_queue" TO console_readonly;
ALTER TABLE public."blocking_tasks" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "blocking_tasks_service_only" ON public."blocking_tasks"; CREATE POLICY "blocking_tasks_service_only" ON public."blocking_tasks" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "blocking_tasks_console_ro" ON public."blocking_tasks"; CREATE POLICY "blocking_tasks_console_ro" ON public."blocking_tasks" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."blocking_tasks" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."blocking_tasks" TO service_role;
GRANT SELECT ON public."blocking_tasks" TO console_readonly;
ALTER TABLE public."boot_briefing_config" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "boot_briefing_config_service_only" ON public."boot_briefing_config"; CREATE POLICY "boot_briefing_config_service_only" ON public."boot_briefing_config" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "boot_briefing_config_console_ro" ON public."boot_briefing_config"; CREATE POLICY "boot_briefing_config_console_ro" ON public."boot_briefing_config" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."boot_briefing_config" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."boot_briefing_config" TO service_role;
GRANT SELECT ON public."boot_briefing_config" TO console_readonly;
ALTER TABLE public."brain_sync_log" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "brain_sync_log_service" ON public."brain_sync_log";
DROP POLICY IF EXISTS "brain_sync_log_service_only" ON public."brain_sync_log"; CREATE POLICY "brain_sync_log_service_only" ON public."brain_sync_log" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "brain_sync_log_console_ro" ON public."brain_sync_log"; CREATE POLICY "brain_sync_log_console_ro" ON public."brain_sync_log" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."brain_sync_log" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."brain_sync_log" TO service_role;
GRANT SELECT ON public."brain_sync_log" TO console_readonly;
ALTER TABLE public."bug_pipeline_readiness" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "service_role full access" ON public."bug_pipeline_readiness";
DROP POLICY IF EXISTS "bug_pipeline_readiness_service_only" ON public."bug_pipeline_readiness"; CREATE POLICY "bug_pipeline_readiness_service_only" ON public."bug_pipeline_readiness" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "bug_pipeline_readiness_console_ro" ON public."bug_pipeline_readiness"; CREATE POLICY "bug_pipeline_readiness_console_ro" ON public."bug_pipeline_readiness" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."bug_pipeline_readiness" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."bug_pipeline_readiness" TO service_role;
GRANT SELECT ON public."bug_pipeline_readiness" TO console_readonly;
ALTER TABLE public."bug_reports" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "service role full access" ON public."bug_reports";
DROP POLICY IF EXISTS "bug_reports_service_only" ON public."bug_reports"; CREATE POLICY "bug_reports_service_only" ON public."bug_reports" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "bug_reports_console_ro" ON public."bug_reports"; CREATE POLICY "bug_reports_console_ro" ON public."bug_reports" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."bug_reports" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."bug_reports" TO service_role;
GRANT SELECT ON public."bug_reports" TO console_readonly;
ALTER TABLE public."build_log" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "service role full access" ON public."build_log";
DROP POLICY IF EXISTS "build_log_service_only" ON public."build_log"; CREATE POLICY "build_log_service_only" ON public."build_log" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "build_log_console_ro" ON public."build_log"; CREATE POLICY "build_log_console_ro" ON public."build_log" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."build_log" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."build_log" TO service_role;
GRANT SELECT ON public."build_log" TO console_readonly;
ALTER TABLE public."cc_cai_audit_log" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "cc_cai_audit_log_service_only" ON public."cc_cai_audit_log"; CREATE POLICY "cc_cai_audit_log_service_only" ON public."cc_cai_audit_log" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "cc_cai_audit_log_console_ro" ON public."cc_cai_audit_log"; CREATE POLICY "cc_cai_audit_log_console_ro" ON public."cc_cai_audit_log" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."cc_cai_audit_log" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."cc_cai_audit_log" TO service_role;
GRANT SELECT ON public."cc_cai_audit_log" TO console_readonly;
ALTER TABLE public."cc_session_costs" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "cc_session_costs_service_only" ON public."cc_session_costs"; CREATE POLICY "cc_session_costs_service_only" ON public."cc_session_costs" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "cc_session_costs_console_ro" ON public."cc_session_costs"; CREATE POLICY "cc_session_costs_console_ro" ON public."cc_session_costs" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."cc_session_costs" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."cc_session_costs" TO service_role;
GRANT SELECT ON public."cc_session_costs" TO console_readonly;
ALTER TABLE public."cc_session_messages" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "cc_session_messages_service_only" ON public."cc_session_messages"; CREATE POLICY "cc_session_messages_service_only" ON public."cc_session_messages" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "cc_session_messages_console_ro" ON public."cc_session_messages"; CREATE POLICY "cc_session_messages_console_ro" ON public."cc_session_messages" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."cc_session_messages" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."cc_session_messages" TO service_role;
GRANT SELECT ON public."cc_session_messages" TO console_readonly;
ALTER TABLE public."cc_work_sessions" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "service role full access" ON public."cc_work_sessions";
DROP POLICY IF EXISTS "cc_work_sessions_service_only" ON public."cc_work_sessions"; CREATE POLICY "cc_work_sessions_service_only" ON public."cc_work_sessions" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "cc_work_sessions_console_ro" ON public."cc_work_sessions"; CREATE POLICY "cc_work_sessions_console_ro" ON public."cc_work_sessions" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."cc_work_sessions" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."cc_work_sessions" TO service_role;
GRANT SELECT ON public."cc_work_sessions" TO console_readonly;
ALTER TABLE public."challenge_enforcer_dryrun_log" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "challenge_enforcer_dryrun_log_service_only" ON public."challenge_enforcer_dryrun_log"; CREATE POLICY "challenge_enforcer_dryrun_log_service_only" ON public."challenge_enforcer_dryrun_log" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "challenge_enforcer_dryrun_log_console_ro" ON public."challenge_enforcer_dryrun_log"; CREATE POLICY "challenge_enforcer_dryrun_log_console_ro" ON public."challenge_enforcer_dryrun_log" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."challenge_enforcer_dryrun_log" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."challenge_enforcer_dryrun_log" TO service_role;
GRANT SELECT ON public."challenge_enforcer_dryrun_log" TO console_readonly;
ALTER TABLE public."client_repos" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "service role full access" ON public."client_repos";
DROP POLICY IF EXISTS "client_repos_service_only" ON public."client_repos"; CREATE POLICY "client_repos_service_only" ON public."client_repos" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "client_repos_console_ro" ON public."client_repos"; CREATE POLICY "client_repos_console_ro" ON public."client_repos" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."client_repos" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."client_repos" TO service_role;
GRANT SELECT ON public."client_repos" TO console_readonly;
ALTER TABLE public."deploy_status" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "deploy_status_service_only" ON public."deploy_status"; CREATE POLICY "deploy_status_service_only" ON public."deploy_status" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "deploy_status_console_ro" ON public."deploy_status"; CREATE POLICY "deploy_status_console_ro" ON public."deploy_status" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."deploy_status" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."deploy_status" TO service_role;
GRANT SELECT ON public."deploy_status" TO console_readonly;
ALTER TABLE public."drift_audits" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "service role full access" ON public."drift_audits";
DROP POLICY IF EXISTS "drift_audits_service_only" ON public."drift_audits"; CREATE POLICY "drift_audits_service_only" ON public."drift_audits" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "drift_audits_console_ro" ON public."drift_audits"; CREATE POLICY "drift_audits_console_ro" ON public."drift_audits" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."drift_audits" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."drift_audits" TO service_role;
GRANT SELECT ON public."drift_audits" TO console_readonly;
ALTER TABLE public."ecosystem_audit_log" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "service role full access" ON public."ecosystem_audit_log";
DROP POLICY IF EXISTS "ecosystem_audit_log_service_only" ON public."ecosystem_audit_log"; CREATE POLICY "ecosystem_audit_log_service_only" ON public."ecosystem_audit_log" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "ecosystem_audit_log_console_ro" ON public."ecosystem_audit_log"; CREATE POLICY "ecosystem_audit_log_console_ro" ON public."ecosystem_audit_log" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."ecosystem_audit_log" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."ecosystem_audit_log" TO service_role;
GRANT SELECT ON public."ecosystem_audit_log" TO console_readonly;
ALTER TABLE public."field_events" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "service_role_all_field_events" ON public."field_events";
DROP POLICY IF EXISTS "field_events_service_only" ON public."field_events"; CREATE POLICY "field_events_service_only" ON public."field_events" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "field_events_console_ro" ON public."field_events"; CREATE POLICY "field_events_console_ro" ON public."field_events" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."field_events" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."field_events" TO service_role;
GRANT SELECT ON public."field_events" TO console_readonly;
ALTER TABLE public."fleet_lanes" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "service role full access" ON public."fleet_lanes";
DROP POLICY IF EXISTS "fleet_lanes_service_only" ON public."fleet_lanes"; CREATE POLICY "fleet_lanes_service_only" ON public."fleet_lanes" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "fleet_lanes_console_ro" ON public."fleet_lanes"; CREATE POLICY "fleet_lanes_console_ro" ON public."fleet_lanes" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."fleet_lanes" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."fleet_lanes" TO service_role;
GRANT SELECT ON public."fleet_lanes" TO console_readonly;
ALTER TABLE public."identity_allowlist" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "identity_allowlist_service_only" ON public."identity_allowlist"; CREATE POLICY "identity_allowlist_service_only" ON public."identity_allowlist" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "identity_allowlist_console_ro" ON public."identity_allowlist"; CREATE POLICY "identity_allowlist_console_ro" ON public."identity_allowlist" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."identity_allowlist" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."identity_allowlist" TO service_role;
GRANT SELECT ON public."identity_allowlist" TO console_readonly;
ALTER TABLE public."ingestion_manifest" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "ingestion_manifest_service_only" ON public."ingestion_manifest"; CREATE POLICY "ingestion_manifest_service_only" ON public."ingestion_manifest" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "ingestion_manifest_console_ro" ON public."ingestion_manifest"; CREATE POLICY "ingestion_manifest_console_ro" ON public."ingestion_manifest" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."ingestion_manifest" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."ingestion_manifest" TO service_role;
GRANT SELECT ON public."ingestion_manifest" TO console_readonly;
ALTER TABLE public."jobs" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "service role full access" ON public."jobs";
DROP POLICY IF EXISTS "jobs_service_only" ON public."jobs"; CREATE POLICY "jobs_service_only" ON public."jobs" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "jobs_console_ro" ON public."jobs"; CREATE POLICY "jobs_console_ro" ON public."jobs" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."jobs" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."jobs" TO service_role;
GRANT SELECT ON public."jobs" TO console_readonly;
ALTER TABLE public."jobs_archive" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "service role full access" ON public."jobs_archive";
DROP POLICY IF EXISTS "jobs_archive_service_only" ON public."jobs_archive"; CREATE POLICY "jobs_archive_service_only" ON public."jobs_archive" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "jobs_archive_console_ro" ON public."jobs_archive"; CREATE POLICY "jobs_archive_console_ro" ON public."jobs_archive" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."jobs_archive" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."jobs_archive" TO service_role;
GRANT SELECT ON public."jobs_archive" TO console_readonly;
ALTER TABLE public."lane_tasks" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "lane_tasks_service_only" ON public."lane_tasks"; CREATE POLICY "lane_tasks_service_only" ON public."lane_tasks" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "lane_tasks_console_ro" ON public."lane_tasks"; CREATE POLICY "lane_tasks_console_ro" ON public."lane_tasks" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."lane_tasks" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."lane_tasks" TO service_role;
GRANT SELECT ON public."lane_tasks" TO console_readonly;
ALTER TABLE public."long_running_claude_callers" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "long_running_claude_callers_service_only" ON public."long_running_claude_callers"; CREATE POLICY "long_running_claude_callers_service_only" ON public."long_running_claude_callers" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "long_running_claude_callers_console_ro" ON public."long_running_claude_callers"; CREATE POLICY "long_running_claude_callers_console_ro" ON public."long_running_claude_callers" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."long_running_claude_callers" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."long_running_claude_callers" TO service_role;
GRANT SELECT ON public."long_running_claude_callers" TO console_readonly;
ALTER TABLE public."message_queue" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "service role full access" ON public."message_queue";
DROP POLICY IF EXISTS "message_queue_service_only" ON public."message_queue"; CREATE POLICY "message_queue_service_only" ON public."message_queue" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "message_queue_console_ro" ON public."message_queue"; CREATE POLICY "message_queue_console_ro" ON public."message_queue" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."message_queue" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."message_queue" TO service_role;
GRANT SELECT ON public."message_queue" TO console_readonly;
ALTER TABLE public."operator_messages" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "operator_messages_service_only" ON public."operator_messages"; CREATE POLICY "operator_messages_service_only" ON public."operator_messages" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "operator_messages_console_ro" ON public."operator_messages"; CREATE POLICY "operator_messages_console_ro" ON public."operator_messages" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."operator_messages" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."operator_messages" TO service_role;
GRANT SELECT ON public."operator_messages" TO console_readonly;
ALTER TABLE public."orchestrator_runtime_config" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "orchestrator_runtime_config_service_only" ON public."orchestrator_runtime_config"; CREATE POLICY "orchestrator_runtime_config_service_only" ON public."orchestrator_runtime_config" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "orchestrator_runtime_config_console_ro" ON public."orchestrator_runtime_config"; CREATE POLICY "orchestrator_runtime_config_console_ro" ON public."orchestrator_runtime_config" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."orchestrator_runtime_config" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."orchestrator_runtime_config" TO service_role;
GRANT SELECT ON public."orchestrator_runtime_config" TO console_readonly;
ALTER TABLE public."platform_admins" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "service_role full access" ON public."platform_admins";
DROP POLICY IF EXISTS "user can see own admin row" ON public."platform_admins";
DROP POLICY IF EXISTS "platform_admins_service_only" ON public."platform_admins"; CREATE POLICY "platform_admins_service_only" ON public."platform_admins" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "platform_admins_console_ro" ON public."platform_admins"; CREATE POLICY "platform_admins_console_ro" ON public."platform_admins" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."platform_admins" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."platform_admins" TO service_role;
GRANT SELECT ON public."platform_admins" TO console_readonly;
ALTER TABLE public."priority_thresholds" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "priority_thresholds_service_only" ON public."priority_thresholds"; CREATE POLICY "priority_thresholds_service_only" ON public."priority_thresholds" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "priority_thresholds_console_ro" ON public."priority_thresholds"; CREATE POLICY "priority_thresholds_console_ro" ON public."priority_thresholds" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."priority_thresholds" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."priority_thresholds" TO service_role;
GRANT SELECT ON public."priority_thresholds" TO console_readonly;
ALTER TABLE public."provisions" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "service role full access" ON public."provisions";
DROP POLICY IF EXISTS "provisions_service_only" ON public."provisions"; CREATE POLICY "provisions_service_only" ON public."provisions" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "provisions_console_ro" ON public."provisions"; CREATE POLICY "provisions_console_ro" ON public."provisions" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."provisions" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."provisions" TO service_role;
GRANT SELECT ON public."provisions" TO console_readonly;
ALTER TABLE public."ralph_state" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "ralph_state_service_only" ON public."ralph_state"; CREATE POLICY "ralph_state_service_only" ON public."ralph_state" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "ralph_state_console_ro" ON public."ralph_state"; CREATE POLICY "ralph_state_console_ro" ON public."ralph_state" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."ralph_state" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."ralph_state" TO service_role;
GRANT SELECT ON public."ralph_state" TO console_readonly;
ALTER TABLE public."repo_context" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "repo_context_read_all" ON public."repo_context";
DROP POLICY IF EXISTS "repo_context_write_service" ON public."repo_context";
DROP POLICY IF EXISTS "repo_context_service_only" ON public."repo_context"; CREATE POLICY "repo_context_service_only" ON public."repo_context" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "repo_context_console_ro" ON public."repo_context"; CREATE POLICY "repo_context_console_ro" ON public."repo_context" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."repo_context" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."repo_context" TO service_role;
GRANT SELECT ON public."repo_context" TO console_readonly;
ALTER TABLE public."repo_events" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "service_role_all_repo_events" ON public."repo_events";
DROP POLICY IF EXISTS "repo_events_service_only" ON public."repo_events"; CREATE POLICY "repo_events_service_only" ON public."repo_events" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "repo_events_console_ro" ON public."repo_events"; CREATE POLICY "repo_events_console_ro" ON public."repo_events" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."repo_events" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."repo_events" TO service_role;
GRANT SELECT ON public."repo_events" TO console_readonly;
ALTER TABLE public."repo_memory" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "service role full access" ON public."repo_memory";
DROP POLICY IF EXISTS "repo_memory_service_only" ON public."repo_memory"; CREATE POLICY "repo_memory_service_only" ON public."repo_memory" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "repo_memory_console_ro" ON public."repo_memory"; CREATE POLICY "repo_memory_console_ro" ON public."repo_memory" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."repo_memory" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."repo_memory" TO service_role;
GRANT SELECT ON public."repo_memory" TO console_readonly;
ALTER TABLE public."repo_snapshot" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "service role full access" ON public."repo_snapshot";
DROP POLICY IF EXISTS "repo_snapshot_service_only" ON public."repo_snapshot"; CREATE POLICY "repo_snapshot_service_only" ON public."repo_snapshot" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "repo_snapshot_console_ro" ON public."repo_snapshot"; CREATE POLICY "repo_snapshot_console_ro" ON public."repo_snapshot" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."repo_snapshot" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."repo_snapshot" TO service_role;
GRANT SELECT ON public."repo_snapshot" TO console_readonly;
ALTER TABLE public."session_digests" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "digests_read_all" ON public."session_digests";
DROP POLICY IF EXISTS "digests_write_service" ON public."session_digests";
DROP POLICY IF EXISTS "session_digests_service_only" ON public."session_digests"; CREATE POLICY "session_digests_service_only" ON public."session_digests" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "session_digests_console_ro" ON public."session_digests"; CREATE POLICY "session_digests_console_ro" ON public."session_digests" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."session_digests" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."session_digests" TO service_role;
GRANT SELECT ON public."session_digests" TO console_readonly;
ALTER TABLE public."strategic_decisions" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "decisions_read_all" ON public."strategic_decisions";
DROP POLICY IF EXISTS "decisions_write_service" ON public."strategic_decisions";
DROP POLICY IF EXISTS "strategic_decisions_service_only" ON public."strategic_decisions"; CREATE POLICY "strategic_decisions_service_only" ON public."strategic_decisions" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "strategic_decisions_console_ro" ON public."strategic_decisions"; CREATE POLICY "strategic_decisions_console_ro" ON public."strategic_decisions" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."strategic_decisions" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."strategic_decisions" TO service_role;
GRANT SELECT ON public."strategic_decisions" TO console_readonly;
ALTER TABLE public."strategic_decisions_archive" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "service role full access" ON public."strategic_decisions_archive";
DROP POLICY IF EXISTS "strategic_decisions_archive_service_only" ON public."strategic_decisions_archive"; CREATE POLICY "strategic_decisions_archive_service_only" ON public."strategic_decisions_archive" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "strategic_decisions_archive_console_ro" ON public."strategic_decisions_archive"; CREATE POLICY "strategic_decisions_archive_console_ro" ON public."strategic_decisions_archive" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."strategic_decisions_archive" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."strategic_decisions_archive" TO service_role;
GRANT SELECT ON public."strategic_decisions_archive" TO console_readonly;
ALTER TABLE public."usage_log" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "service role full access" ON public."usage_log";
DROP POLICY IF EXISTS "usage_log_service_only" ON public."usage_log"; CREATE POLICY "usage_log_service_only" ON public."usage_log" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "usage_log_console_ro" ON public."usage_log"; CREATE POLICY "usage_log_console_ro" ON public."usage_log" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."usage_log" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."usage_log" TO service_role;
GRANT SELECT ON public."usage_log" TO console_readonly;
ALTER TABLE public."watchdog_calibration_observations" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "watchdog_calibration_observations_service_only" ON public."watchdog_calibration_observations"; CREATE POLICY "watchdog_calibration_observations_service_only" ON public."watchdog_calibration_observations" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "watchdog_calibration_observations_console_ro" ON public."watchdog_calibration_observations"; CREATE POLICY "watchdog_calibration_observations_console_ro" ON public."watchdog_calibration_observations" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."watchdog_calibration_observations" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."watchdog_calibration_observations" TO service_role;
GRANT SELECT ON public."watchdog_calibration_observations" TO console_readonly;
ALTER TABLE public."watchdog_monitored_callers" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "watchdog_monitored_callers_service_only" ON public."watchdog_monitored_callers"; CREATE POLICY "watchdog_monitored_callers_service_only" ON public."watchdog_monitored_callers" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "watchdog_monitored_callers_console_ro" ON public."watchdog_monitored_callers"; CREATE POLICY "watchdog_monitored_callers_console_ro" ON public."watchdog_monitored_callers" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."watchdog_monitored_callers" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."watchdog_monitored_callers" TO service_role;
GRANT SELECT ON public."watchdog_monitored_callers" TO console_readonly;
ALTER TABLE public."wingmen_brain" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "wingmen_brain_service" ON public."wingmen_brain";
DROP POLICY IF EXISTS "wingmen_brain_service_only" ON public."wingmen_brain"; CREATE POLICY "wingmen_brain_service_only" ON public."wingmen_brain" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "wingmen_brain_console_ro" ON public."wingmen_brain"; CREATE POLICY "wingmen_brain_console_ro" ON public."wingmen_brain" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."wingmen_brain" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."wingmen_brain" TO service_role;
GRANT SELECT ON public."wingmen_brain" TO console_readonly;
ALTER TABLE public."work_outputs" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "service role full access" ON public."work_outputs";
DROP POLICY IF EXISTS "work_outputs_service_only" ON public."work_outputs"; CREATE POLICY "work_outputs_service_only" ON public."work_outputs" FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "work_outputs_console_ro" ON public."work_outputs"; CREATE POLICY "work_outputs_console_ro" ON public."work_outputs" FOR SELECT TO console_readonly USING (true);
REVOKE ALL ON public."work_outputs" FROM anon, authenticated, PUBLIC;
GRANT ALL ON public."work_outputs" TO service_role;
GRANT SELECT ON public."work_outputs" TO console_readonly;
COMMIT;
