-- 035: operator_backlog — the operator's REALTIME "Your asks" tracker (op#9088).
--
-- The Fleet Console folds in a live backlog section: instead of regenerating a
-- static reports/operator-asks-backlog.html page, the console reads this table on
-- its normal /api/fleet poll, so the running list of what the operator has asked
-- for (with status) is always one place to look and refreshes itself. Nazim (the
-- service role) curates the rows; the read-only console role only SELECTs.
--
-- Apply via scripts/apply_migration.py 035 --silo tscuymavysscrvoberrr (historical
-- applier: apply_operator_backlog.py, deleted 2026-09-05 PR #90; decision-962: NEVER
-- `supabase db push`). RLS + grant shape mirrors migration 013:
-- service_role owns it, console_readonly gets SELECT, everyone else is revoked.

BEGIN;

CREATE TABLE IF NOT EXISTS public.operator_backlog (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ask         text NOT NULL,
  status      text NOT NULL CHECK (status IN ('needs_you','in_progress','done','parked')),
  op_ref      text,
  note        text,
  sort_order  int NOT NULL DEFAULT 0,
  updated_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.operator_backlog ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS operator_backlog_service_only ON public.operator_backlog;
CREATE POLICY operator_backlog_service_only ON public.operator_backlog
  FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS operator_backlog_console_ro ON public.operator_backlog;
CREATE POLICY operator_backlog_console_ro ON public.operator_backlog
  FOR SELECT TO console_readonly USING (true);

REVOKE ALL ON public.operator_backlog FROM anon, authenticated, PUBLIC;
GRANT ALL ON public.operator_backlog TO service_role;
GRANT SELECT ON public.operator_backlog TO console_readonly;

COMMIT;
