-- 044: operator_asks — the console's LIVE "Your asks" ledger (replaces the stale
-- operator_backlog "Your asks", migration 035).
--
-- The operator (Musa) asked to SEE the things he asks of Nazim and Nazim
-- delegates — with LIVE status, never a stored snapshot (op#13250: "this cannot
-- be stale info"). operator_backlog stored a hand-curated `status` text that went
-- stale the instant a lane moved and Nazim forgot to re-edit; that IS the bug.
--
-- This ledger stores ONLY immutable facts: the ask text, the originating
-- operator_messages id, and a `thread_id` link to the delegated agent_messages
-- directive. STATUS IS NEVER STORED HERE — it is derived live from the linked
-- agent_messages row (read_at/responded_at/direction) on every /api/fleet poll,
-- so it structurally cannot be stale. The only mutable columns are the operator's
-- own swipe-to-confirm close (confirmed_at/closed_at) — "a lane replied" is NOT
-- "the operator confirmed it landed."
--
-- DEVIATION from reports/console-overhaul/your-asks-board-design.md §4: the design
-- sketched `thread_id text`, but the live `agent_messages.thread_id` column is
-- `uuid` (set via gen_random_uuid(); see scripts/fleet_stall_watch.py,
-- scripts/watchdog_tripwire_report.py). Per the build brief "trust the live code":
-- operator_asks.thread_id is `uuid` so the derive-query join is type-clean.
--
-- source_msg_id references operator_messages.id, which lives in the SEPARATE
-- operator DB (two-DB split) — so it is a plain bigint, NOT a FK (no cross-DB
-- constraint), exactly as the design notes.
--
-- Apply via direct psycopg (decision-962: NEVER `supabase db push`) —
-- scripts/apply_operator_asks.py. RLS + grant shape mirrors migration 035:
-- service_role owns it, console_readonly gets SELECT, everyone else is revoked.

BEGIN;

CREATE TABLE IF NOT EXISTS public.operator_asks (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ask           text        NOT NULL,             -- the operator's ask, distilled (immutable)
  source_msg_id bigint,                           -- operator_messages.id that raised it (cross-DB; nullable → "asked Xm ago")
  thread_id     uuid,                             -- agent_messages.thread_id link (nullable → not yet delegated = on_nazim)
  delegated_to  text,                             -- denormalized to_agent for display (cheap; from the directive)
  created_at    timestamptz NOT NULL DEFAULT now(),
  confirmed_at  timestamptz,                      -- operator swiped-to-confirm a delegate_done → REAL done (≠ delegate-replied)
  closed_at     timestamptz,                      -- ask leaves the live board (set on confirm OR drop)
  closed_reason text                              -- 'operator_done' | 'dropped'
);

-- Open asks are the hot read (the live board filters closed_at IS NULL).
CREATE INDEX IF NOT EXISTS operator_asks_open_idx
  ON public.operator_asks (created_at) WHERE closed_at IS NULL;

-- The derive-query joins operator_asks.thread_id → agent_messages.thread_id.
CREATE INDEX IF NOT EXISTS operator_asks_thread_idx
  ON public.operator_asks (thread_id) WHERE thread_id IS NOT NULL;

ALTER TABLE public.operator_asks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS operator_asks_service_only ON public.operator_asks;
CREATE POLICY operator_asks_service_only ON public.operator_asks
  FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS operator_asks_console_ro ON public.operator_asks;
CREATE POLICY operator_asks_console_ro ON public.operator_asks
  FOR SELECT TO console_readonly USING (true);

REVOKE ALL ON public.operator_asks FROM anon, authenticated, PUBLIC;
GRANT ALL    ON public.operator_asks TO service_role;
GRANT SELECT ON public.operator_asks TO console_readonly;

COMMIT;
