-- 075_operator_backlog_seq_resync.sql
-- ledger: silo=tscuymavysscrvoberrr
-- (orchestrator substrate)
--
-- Fixes bus #44205 (orch-console, P3): operator_backlog.id is
-- `GENERATED BY DEFAULT AS IDENTITY` (migration 035) -- BY DEFAULT (not
-- ALWAYS) means an explicit id in an INSERT is accepted rather than
-- rejected, so operator_backlog_id_seq can silently fall behind max(id)
-- whenever a row is curated with an explicit id (migration 035's own header:
-- "Nazim (the service role) curates the rows" -- this is direct/manual
-- curation, not a scripted writer; grep of every writer in this repo
-- (scripts/backlog_swipe.py, scripts/backlog_done_checker.py,
-- nervous_system/console/*) found only UPDATEs, no INSERTs, so there is no
-- in-repo script to fix -- the gap is in the curation habit, not the code).
-- orch-console hit this live: a default-id insert collided with id 70
-- (already occupied), and worked around it with an explicit id 74.
--
-- Pure data: realigns the identity sequence to the table's actual max id so
-- the next default-id insert doesn't collide again. Idempotent -- rerunning
-- this after further explicit-id inserts just resyncs again; a genuinely
-- empty table falls back to 1 rather than erroring on NULL max(id). No
-- privilege change, so no `-- assert:` lines are needed (house convention
-- per migrations 065/069/070/071/073/074 headers).
--
-- NOTE (not fixed here, no code change needed): future curatorial inserts
-- into operator_backlog should omit `id` and let the identity default
-- assign it, to avoid re-lagging the sequence.
--
-- REVERT: not meaningful -- a sequence position has no prior value worth
-- restoring to (it would just re-introduce the collision this fixes).

SELECT setval(
  'public.operator_backlog_id_seq',
  COALESCE((SELECT max(id) FROM public.operator_backlog), 1)
);
