"""CADENCE-008 A: drain_token_ledger table (psycopg-apply, decision-962 safe).

Tracks per-cycle token spend so the ihsanos-drain runner can enforce a daily cap.
CLAUDE.md forbids `supabase db push` against prod; use this direct psycopg-apply.

Usage:
  python scripts/apply_drain_token_ledger.py            # dry-run (no writes)
  python scripts/apply_drain_token_ledger.py --apply    # commit
"""
from __future__ import annotations

import os
import sys

import psycopg
from dotenv import load_dotenv

APPLY_SQL = """
create table if not exists drain_token_ledger (
    id           bigint generated by default as identity primary key,
    caller_name  text not null,
    cycle_at     timestamptz not null default now(),
    tokens_spent integer not null default 0,
    note         text
);
create index if not exists drain_token_ledger_caller_day_idx
    on drain_token_ledger (caller_name, cycle_at);
"""


def main() -> int:
    apply = "--apply" in sys.argv
    load_dotenv("/Users/sheikhmusa/wingmen/orchestrator/.env")
    dsn = os.environ.get("DATABASE_URL") or os.environ.get("SUPABASE_DB_URL")
    if not dsn:
        raise SystemExit("DATABASE_URL / SUPABASE_DB_URL not set")
    with psycopg.connect(dsn) as conn, conn.cursor() as cur:
        cur.execute(APPLY_SQL)
        cur.execute("select to_regclass('public.drain_token_ledger')")
        assert cur.fetchone()[0] is not None, "table not created"
        if apply:
            conn.commit()
            print("APPLIED drain_token_ledger.")
        else:
            conn.rollback()
            print("DRY-RUN (rolled back). Re-run with --apply to commit.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
