#!/usr/bin/env python3
"""gen_data_store_registry.py — regenerate the per-org classification table in
docs/data-store-registry.md from the data_provenance table (migration 089).

op#25626 / bus #51657/#51670: docs/data-store-registry.md's per-org
classifications become GENERATED from data_provenance (one source of truth)
instead of hand-maintained prose that can drift from what actually got
reseeded/migrated. Only the block between the GENERATED markers is rewritten;
everything else in the doc (the store-level table, Firebase section, etc.)
stays hand-authored.
"""
from __future__ import annotations

import os
import sys

import psycopg

sys.path.insert(0, os.path.dirname(__file__))
import bus_send  # noqa: E402 — reuse its dburl() so DSN resolution has one owner

DOC_PATH = os.path.join(os.path.dirname(__file__), "..", "docs", "data-store-registry.md")
START = "<!-- GENERATED:data_provenance:START -->"
END = "<!-- GENERATED:data_provenance:END -->"


def render_table(rows: list[tuple]) -> str:
    lines = [
        "| Project ref | Org | Classification | Evidence | Owner | Updated |",
        "|---|---|---|---|---|---|",
    ]
    for project_ref, org_id, org_name, alias, classification, evidence, owner, updated_at in rows:
        org_label = org_name or org_id or "(store-level)"
        evidence_short = evidence if len(evidence) <= 200 else evidence[:197] + "..."
        lines.append(
            f"| `{project_ref}` | {org_label} ({alias}) | **{classification}** | "
            f"{evidence_short} | {owner or ''} | {updated_at} |"
        )
    lines.append("")
    lines.append(
        "Generated by `scripts/gen_data_store_registry.py` — edit `data_provenance` "
        "(with evidence), not this block."
    )
    return "\n".join(lines)


def main() -> int:
    dsn = bus_send.dburl(os.environ)
    with psycopg.connect(dsn) as conn, conn.cursor() as cur:
        cur.execute(
            "select project_ref, org_id, org_name, alias, classification, evidence, owner, updated_at "
            "from data_provenance order by project_ref, org_id"
        )
        rows = cur.fetchall()

    if not rows:
        print("no data_provenance rows — has migration 089 been applied?", file=sys.stderr)
        return 1

    table = render_table(rows)

    with open(DOC_PATH) as f:
        doc = f.read()

    if START not in doc or END not in doc:
        print(f"markers {START!r}/{END!r} not found in {DOC_PATH}", file=sys.stderr)
        return 1

    pre, _, rest = doc.partition(START)
    _, _, post = rest.partition(END)
    new_doc = f"{pre}{START}\n{table}\n{END}{post}"

    with open(DOC_PATH, "w") as f:
        f.write(new_doc)

    print(f"regenerated {len(rows)} rows into {DOC_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
